// Mock dataset for TelcoShark Phase 1 (UI-only).
// A typed TS module rather than a JSON file: the decode trees are recursive
// and cross-referenced by frame number (CallFlowEvent.frameNumber must exist
// as a RawPacket.frameNumber) — hand-balancing that in raw JSON is error-prone
// and only checkable at runtime, whereas this gets caught by tsc.
//
// Four scenarios, per the edge-case spec this dataset is built to exercise:
//   User A — multi-PDU-session (internet + ims concurrently), clean end to end
//   User B — Registration Reject, never reaches a PDU session
//   User C — mid-stream capture: no Registration observed, starts at an Update
//   Noise  — DNS/NTP/ARP/inter-NF traffic with no correlatedSupi at all

import { assignByteRanges, generateHexDump } from "./utils";
import type {
  CallFlowEvent,
  CorrelationEntry,
  MockDataset,
  ProtocolNode,
  RawPacket,
  SessionIdentity,
} from "./types";

const USER_A_SUPI = "imsi-001010123456789";
const USER_B_SUPI = "imsi-001010987654321";
const USER_C_SUPI = "imsi-001010555555555";

const sessionIdentities: SessionIdentity[] = [
  { supi: USER_A_SUPI, guti: "001-01-8001-0002-C3F1A9", msisdn: "12015550123", imei: "358752119876543", captureStatus: "complete" },
  // Rejected before GUTI assignment / subscriber-profile lookup — there is genuinely nothing else to show.
  { supi: USER_B_SUPI, captureStatus: "complete" },
  // Capture starts after Registration — GUTI/MSISDN/IMEI were never observed, not just omitted.
  { supi: USER_C_SUPI, captureStatus: "mid-stream" },
];

// ---------------------------------------------------------------------------
// Decode-tree helpers
// ---------------------------------------------------------------------------

function baseLayers(opts: {
  frameNumber: number;
  length: number;
  srcIp: string;
  srcPort: number;
  dstIp: string;
  dstPort: number;
  transport: "SCTP" | "TCP" | "UDP";
}): ProtocolNode[] {
  const idp = `f${opts.frameNumber}`;
  const transportLabel =
    opts.transport === "SCTP"
      ? "Stream Control Transmission Protocol"
      : opts.transport === "TCP"
        ? "Transmission Control Protocol"
        : "User Datagram Protocol";
  return [
    { id: `${idp}-frame`, label: `Frame ${opts.frameNumber}`, detail: `${opts.length} bytes on wire (${opts.length * 8} bits)` },
    { id: `${idp}-eth`, label: "Ethernet II", detail: "capture point: core-network mirror port" },
    {
      id: `${idp}-ip`,
      label: "Internet Protocol Version 4",
      detail: `Src: ${opts.srcIp}, Dst: ${opts.dstIp}`,
      children: [
        { id: `${idp}-ip-src`, label: "Source Address", detail: opts.srcIp },
        { id: `${idp}-ip-dst`, label: "Destination Address", detail: opts.dstIp },
      ],
    },
    { id: `${idp}-transport`, label: transportLabel, detail: `Src Port: ${opts.srcPort}, Dst Port: ${opts.dstPort}` },
  ];
}

function objectToNodes(obj: Record<string, unknown>, idPrefix: string): ProtocolNode[] {
  return Object.entries(obj).map(([key, value], i) => {
    const id = `${idPrefix}-${key}-${i}`;
    if (value !== null && typeof value === "object" && !Array.isArray(value)) {
      return { id, label: key, children: objectToNodes(value as Record<string, unknown>, id) };
    }
    return { id, label: key, detail: JSON.stringify(value) };
  });
}

// ---------------------------------------------------------------------------
// Raw packet seeds (decodeTree byteRanges + hexDump filled in below)
// ---------------------------------------------------------------------------

type PacketSeed = Omit<RawPacket, "hexDump">;

const packetSeeds: PacketSeed[] = [
  // ---- Frames 1–14: User A Session #5 (internet) + User B reject + noise DNS query ----
  {
    frameNumber: 1,
    timestamp: "2026-08-19T01:05:12.100000Z",
    epochMicroseconds: 1755565512100000,
    srcIp: "192.0.2.109",
    srcPort: 51820,
    dstIp: "192.0.2.62",
    dstPort: 53,
    protocol: "DNS",
    length: 74,
    info: "Standard query 0x1a2b A pool.ntp.mnc001.mcc001.gprs",
    domain: "USER_PLANE_N4_N3",
    status: "INFO",
    decodeTree: [
      ...baseLayers({ frameNumber: 1, length: 74, srcIp: "192.0.2.109", srcPort: 51820, dstIp: "192.0.2.62", dstPort: 53, transport: "UDP" }),
      {
        id: "f1-dns",
        label: "Domain Name System",
        detail: "Standard query 0x1a2b A pool.ntp.mnc001.mcc001.gprs",
        children: [
          {
            id: "f1-dns-q",
            label: "Queries",
            children: [
              { id: "f1-dns-qname", label: "Name", detail: "pool.ntp.mnc001.mcc001.gprs" },
              { id: "f1-dns-qtype", label: "Type", detail: "A" },
            ],
          },
        ],
      },
    ],
  },
  {
    frameNumber: 2,
    timestamp: "2026-08-19T01:05:12.112384Z",
    epochMicroseconds: 1755565512112384,
    srcIp: "192.0.2.10",
    srcPort: 51001,
    dstIp: "192.0.2.20",
    dstPort: 38412,
    protocol: "NGAP",
    length: 168,
    info: "InitialUEMessage, RAN-UE-NGAP-ID: 1042, Registration Request",
    domain: "ACCESS_N1_N2",
    correlatedSupi: USER_A_SUPI,
    status: "INFO",
    decodeTree: [
      ...baseLayers({ frameNumber: 2, length: 168, srcIp: "192.0.2.10", srcPort: 51001, dstIp: "192.0.2.20", dstPort: 38412, transport: "SCTP" }),
      {
        id: "f2-ngap",
        label: "NG Application Protocol",
        detail: "InitialUEMessage",
        children: [
          { id: "f2-ngap-ranid", label: "RAN-UE-NGAP-ID", detail: "1042" },
          {
            id: "f2-ngap-naspdu",
            label: "NAS-PDU",
            detail: "Registration Request",
            children: [
              { id: "f2-nas-type", label: "5GS Registration Type", detail: "initial-registration" },
              { id: "f2-nas-suci", label: "5GS Mobile Identity", detail: "SUCI: suci-0-001-01-0000-0-0-a1b2c3d4" },
            ],
          },
          {
            id: "f2-ngap-uli",
            label: "UserLocationInformation",
            detail: "NR CGI",
            children: [
              { id: "f2-uli-plmn", label: "PLMN Identity", detail: "00101" },
              { id: "f2-uli-cell", label: "NR Cell Identity", detail: "0x000000A1B2C3" },
              { id: "f2-uli-tac", label: "TAC", detail: "0x8001" },
            ],
          },
        ],
      },
    ],
  },
  {
    frameNumber: 3,
    timestamp: "2026-08-19T01:05:12.118940Z",
    epochMicroseconds: 1755565512118940,
    srcIp: "192.0.2.10",
    srcPort: 51002,
    dstIp: "192.0.2.20",
    dstPort: 38412,
    protocol: "NGAP",
    length: 152,
    info: "InitialUEMessage, RAN-UE-NGAP-ID: 2091, Registration Request",
    domain: "ACCESS_N1_N2",
    correlatedSupi: USER_B_SUPI,
    status: "INFO",
    decodeTree: [
      ...baseLayers({ frameNumber: 3, length: 152, srcIp: "192.0.2.10", srcPort: 51002, dstIp: "192.0.2.20", dstPort: 38412, transport: "SCTP" }),
      {
        id: "f3-ngap",
        label: "NG Application Protocol",
        detail: "InitialUEMessage",
        children: [
          { id: "f3-ngap-ranid", label: "RAN-UE-NGAP-ID", detail: "2091" },
          {
            id: "f3-ngap-naspdu",
            label: "NAS-PDU",
            detail: "Registration Request",
            children: [{ id: "f3-nas-suci", label: "5GS Mobile Identity", detail: "SUCI: suci-0-001-01-0000-0-0-ffeeddcc" }],
          },
        ],
      },
    ],
  },
  {
    frameNumber: 4,
    timestamp: "2026-08-19T01:05:12.134221Z",
    epochMicroseconds: 1755565512134221,
    srcIp: "192.0.2.20",
    srcPort: 44210,
    dstIp: "192.0.2.50",
    dstPort: 8080,
    protocol: "HTTP2/JSON",
    length: 428,
    info: "POST /nausf-auth/v1/ue-authentications, 201 Created",
    domain: "CORE_SBI",
    correlatedSupi: USER_A_SUPI,
    status: "SUCCESS",
    decodeTree: [
      ...baseLayers({ frameNumber: 4, length: 428, srcIp: "192.0.2.20", srcPort: 44210, dstIp: "192.0.2.50", dstPort: 8080, transport: "TCP" }),
      {
        id: "f4-http2",
        label: "HTTP/2",
        detail: "POST /nausf-auth/v1/ue-authentications",
        children: [
          { id: "f4-h2-status", label: ":status", detail: "201" },
          {
            id: "f4-h2-body",
            label: "JSON Body",
            children: objectToNodes(
              {
                supiOrSuci: "suci-0-001-01-0000-0-0-a1b2c3d4",
                servingNetworkName: "5G:mnc001.mcc001.3gppnetwork.org",
                authType: "5G_AKA",
                authCtxId: "auth-ctx-77af21",
                "5gAuthData": { rand: "3f8a...c11e", autn: "9be2...004a", hxresStar: "d0a1...77bf" },
              },
              "f4-body",
            ),
          },
        ],
      },
    ],
  },
  {
    frameNumber: 5,
    timestamp: "2026-08-19T01:05:12.151077Z",
    epochMicroseconds: 1755565512151077,
    srcIp: "192.0.2.20",
    srcPort: 38412,
    dstIp: "192.0.2.10",
    dstPort: 51002,
    protocol: "NGAP",
    length: 96,
    info: "DownlinkNASTransport, RAN-UE-NGAP-ID: 2091, Registration Reject (PLMN not allowed)",
    domain: "ACCESS_N1_N2",
    correlatedSupi: USER_B_SUPI,
    status: "ERROR",
    decodeTree: [
      ...baseLayers({ frameNumber: 5, length: 96, srcIp: "192.0.2.20", srcPort: 38412, dstIp: "192.0.2.10", dstPort: 51002, transport: "SCTP" }),
      {
        id: "f5-ngap",
        label: "NG Application Protocol",
        detail: "DownlinkNASTransport",
        children: [
          { id: "f5-amfid", label: "AMF-UE-NGAP-ID", detail: "500311" },
          { id: "f5-ranid", label: "RAN-UE-NGAP-ID", detail: "2091" },
          {
            id: "f5-naspdu",
            label: "NAS-PDU",
            detail: "Registration Reject",
            children: [{ id: "f5-cause", label: "5GMM Cause", detail: "#11 PLMN not allowed" }],
          },
        ],
      },
    ],
  },
  {
    frameNumber: 6,
    timestamp: "2026-08-19T01:05:12.158652Z",
    epochMicroseconds: 1755565512158652,
    srcIp: "192.0.2.20",
    srcPort: 38412,
    dstIp: "192.0.2.10",
    dstPort: 51001,
    protocol: "NGAP",
    length: 132,
    info: "DownlinkNASTransport, RAN-UE-NGAP-ID: 1042, Authentication Request",
    domain: "ACCESS_N1_N2",
    correlatedSupi: USER_A_SUPI,
    status: "INFO",
    decodeTree: [
      ...baseLayers({ frameNumber: 6, length: 132, srcIp: "192.0.2.20", srcPort: 38412, dstIp: "192.0.2.10", dstPort: 51001, transport: "SCTP" }),
      {
        id: "f6-ngap",
        label: "NG Application Protocol",
        detail: "DownlinkNASTransport",
        children: [
          { id: "f6-amfid", label: "AMF-UE-NGAP-ID", detail: "500219" },
          { id: "f6-ranid", label: "RAN-UE-NGAP-ID", detail: "1042" },
          {
            id: "f6-naspdu",
            label: "NAS-PDU",
            detail: "Authentication Request",
            children: [
              { id: "f6-rand", label: "RAND", detail: "3f8a…c11e" },
              { id: "f6-autn", label: "AUTN", detail: "9be2…004a" },
            ],
          },
        ],
      },
    ],
  },
  {
    frameNumber: 7,
    timestamp: "2026-08-19T01:05:12.191340Z",
    epochMicroseconds: 1755565512191340,
    srcIp: "192.0.2.10",
    srcPort: 51001,
    dstIp: "192.0.2.20",
    dstPort: 38412,
    protocol: "NGAP",
    length: 118,
    info: "UplinkNASTransport, RAN-UE-NGAP-ID: 1042, Authentication Response",
    domain: "ACCESS_N1_N2",
    correlatedSupi: USER_A_SUPI,
    status: "SUCCESS",
    decodeTree: [
      ...baseLayers({ frameNumber: 7, length: 118, srcIp: "192.0.2.10", srcPort: 51001, dstIp: "192.0.2.20", dstPort: 38412, transport: "SCTP" }),
      {
        id: "f7-ngap",
        label: "NG Application Protocol",
        detail: "UplinkNASTransport",
        children: [
          { id: "f7-amfid", label: "AMF-UE-NGAP-ID", detail: "500219" },
          { id: "f7-ranid", label: "RAN-UE-NGAP-ID", detail: "1042" },
          {
            id: "f7-naspdu",
            label: "NAS-PDU",
            detail: "Authentication Response",
            children: [{ id: "f7-res", label: "RES*", detail: "d0a1…77bf" }],
          },
        ],
      },
    ],
  },
  {
    frameNumber: 8,
    timestamp: "2026-08-19T01:05:12.220981Z",
    epochMicroseconds: 1755565512220981,
    srcIp: "192.0.2.20",
    srcPort: 44300,
    dstIp: "192.0.2.30",
    dstPort: 8080,
    protocol: "HTTP2/JSON",
    length: 512,
    info: "POST /nsmf-pdusession/v1/sm-contexts, 201 Created (Session #5)",
    domain: "CORE_SBI",
    correlatedSupi: USER_A_SUPI,
    status: "SUCCESS",
    decodeTree: [
      ...baseLayers({ frameNumber: 8, length: 512, srcIp: "192.0.2.20", srcPort: 44300, dstIp: "192.0.2.30", dstPort: 8080, transport: "TCP" }),
      {
        id: "f8-http2",
        label: "HTTP/2",
        detail: "POST /nsmf-pdusession/v1/sm-contexts",
        children: [
          { id: "f8-h2-status", label: ":status", detail: "201" },
          {
            id: "f8-h2-body",
            label: "JSON Body",
            children: objectToNodes(
              {
                supi: USER_A_SUPI,
                pduSessionId: 5,
                dnn: "internet",
                sNssai: { sst: 1, sd: "000001" },
                anType: "3GPP_ACCESS",
                smContextStatusUri: "http://amf.5gc.mnc001.mcc001.3gppnetwork.org/namf-callback/v1/smContextStatus/5",
              },
              "f8-body",
            ),
          },
        ],
      },
    ],
  },
  {
    frameNumber: 9,
    timestamp: "2026-08-19T01:05:12.256410Z",
    epochMicroseconds: 1755565512256410,
    srcIp: "192.0.2.30",
    srcPort: 8805,
    dstIp: "192.0.2.40",
    dstPort: 8805,
    protocol: "PFCP",
    length: 176,
    info: "Session Establishment Request, 2 PDR, 2 FAR (Session #5)",
    domain: "USER_PLANE_N4_N3",
    correlatedSupi: USER_A_SUPI,
    status: "INFO",
    decodeTree: [
      ...baseLayers({ frameNumber: 9, length: 176, srcIp: "192.0.2.30", srcPort: 8805, dstIp: "192.0.2.40", dstPort: 8805, transport: "UDP" }),
      {
        id: "f9-pfcp",
        label: "Packet Forwarding Control Protocol",
        detail: "Session Establishment Request",
        children: [
          {
            id: "f9-pdr1",
            label: "Create PDR (PDR ID 1)",
            detail: "Precedence 100",
            children: [
              { id: "f9-pdr1-pdi", label: "PDI", detail: "Source Interface: Access, Local F-TEID 0x2F3A9C11, UE IP 192.0.2.122" },
              { id: "f9-pdr1-far", label: "FAR ID", detail: "1" },
            ],
          },
          {
            id: "f9-pdr2",
            label: "Create PDR (PDR ID 2)",
            detail: "Precedence 100",
            children: [
              { id: "f9-pdr2-pdi", label: "PDI", detail: "Source Interface: Core, Network Instance internet" },
              { id: "f9-pdr2-far", label: "FAR ID", detail: "2" },
            ],
          },
          {
            id: "f9-far1",
            label: "Create FAR (FAR ID 1)",
            detail: "Apply Action: FORW",
            children: [{ id: "f9-far1-fp", label: "Forwarding Parameters", detail: "Destination Interface: Core" }],
          },
          {
            id: "f9-far2",
            label: "Create FAR (FAR ID 2)",
            detail: "Apply Action: FORW",
            children: [
              { id: "f9-far2-fp", label: "Forwarding Parameters", detail: "Destination Interface: Access, Outer Header Creation: GTP-U/UDP/IPv4 TEID 0x88F10A02" },
            ],
          },
        ],
      },
    ],
  },
  {
    frameNumber: 10,
    timestamp: "2026-08-19T01:05:12.279650Z",
    epochMicroseconds: 1755565512279650,
    srcIp: "192.0.2.40",
    srcPort: 8805,
    dstIp: "192.0.2.30",
    dstPort: 8805,
    protocol: "PFCP",
    length: 108,
    info: "Session Establishment Response, Cause: Request accepted (Session #5)",
    domain: "USER_PLANE_N4_N3",
    correlatedSupi: USER_A_SUPI,
    status: "SUCCESS",
    decodeTree: [
      ...baseLayers({ frameNumber: 10, length: 108, srcIp: "192.0.2.40", srcPort: 8805, dstIp: "192.0.2.30", dstPort: 8805, transport: "UDP" }),
      {
        id: "f10-pfcp",
        label: "Packet Forwarding Control Protocol",
        detail: "Session Establishment Response",
        children: [
          { id: "f10-cause", label: "Cause", detail: "Request accepted" },
          { id: "f10-fteid", label: "Created PDR (PDR ID 1)", detail: "Assigned F-TEID 0x2F3A9C11" },
        ],
      },
    ],
  },
  {
    frameNumber: 11,
    timestamp: "2026-08-19T01:05:12.304822Z",
    epochMicroseconds: 1755565512304822,
    srcIp: "192.0.2.30",
    srcPort: 44301,
    dstIp: "192.0.2.20",
    dstPort: 8080,
    protocol: "HTTP2/JSON",
    length: 302,
    info: "POST /nsmf-pdusession/v1/sm-contexts/5/modify, 200 OK",
    domain: "CORE_SBI",
    correlatedSupi: USER_A_SUPI,
    status: "SUCCESS",
    decodeTree: [
      ...baseLayers({ frameNumber: 11, length: 302, srcIp: "192.0.2.30", srcPort: 44301, dstIp: "192.0.2.20", dstPort: 8080, transport: "TCP" }),
      {
        id: "f11-http2",
        label: "HTTP/2",
        detail: "POST /nsmf-pdusession/v1/sm-contexts/5/modify",
        children: [
          { id: "f11-h2-status", label: ":status", detail: "200" },
          {
            id: "f11-h2-body",
            label: "JSON Body",
            children: objectToNodes(
              { pduSessionId: 5, upCnxState: "ACTIVATED", n2SmInfoType: "PDU_RES_SETUP_REQ", n1SmMsgType: "PDU_SESSION_ESTABLISHMENT_ACCEPT" },
              "f11-body",
            ),
          },
        ],
      },
    ],
  },
  {
    frameNumber: 12,
    timestamp: "2026-08-19T01:05:12.331509Z",
    epochMicroseconds: 1755565512331509,
    srcIp: "192.0.2.20",
    srcPort: 38412,
    dstIp: "192.0.2.10",
    dstPort: 51001,
    protocol: "NGAP",
    length: 184,
    info: "PDUSessionResourceSetupRequest, PDU Session ID: 5",
    domain: "ACCESS_N1_N2",
    correlatedSupi: USER_A_SUPI,
    status: "INFO",
    decodeTree: [
      ...baseLayers({ frameNumber: 12, length: 184, srcIp: "192.0.2.20", srcPort: 38412, dstIp: "192.0.2.10", dstPort: 51001, transport: "SCTP" }),
      {
        id: "f12-ngap",
        label: "NG Application Protocol",
        detail: "PDUSessionResourceSetupRequest",
        children: [
          { id: "f12-amfid", label: "AMF-UE-NGAP-ID", detail: "500219" },
          { id: "f12-ranid", label: "RAN-UE-NGAP-ID", detail: "1042" },
          {
            id: "f12-list",
            label: "PDUSessionResourceSetupListSUReq",
            detail: "1 item",
            children: [
              { id: "f12-pdusid", label: "PDUSessionID", detail: "5" },
              { id: "f12-ul-tnl", label: "UL-NGU-UP-TNLInformation", detail: "GTP-TEID 0x2F3A9C11, transportLayerAddress 192.0.2.40" },
            ],
          },
        ],
      },
    ],
  },
  {
    frameNumber: 13,
    timestamp: "2026-08-19T01:05:12.368274Z",
    epochMicroseconds: 1755565512368274,
    srcIp: "192.0.2.10",
    srcPort: 2152,
    dstIp: "192.0.2.40",
    dstPort: 2152,
    protocol: "GTP-U",
    length: 62,
    info: "Echo Request (Session #5)",
    domain: "USER_PLANE_N4_N3",
    correlatedSupi: USER_A_SUPI,
    status: "INFO",
    decodeTree: [
      ...baseLayers({ frameNumber: 13, length: 62, srcIp: "192.0.2.10", srcPort: 2152, dstIp: "192.0.2.40", dstPort: 2152, transport: "UDP" }),
      {
        id: "f13-gtpu",
        label: "GPRS Tunnelling Protocol",
        detail: "Echo Request",
        children: [
          { id: "f13-flags", label: "Flags", detail: "Version 1, PT: GTP, no optional headers" },
          { id: "f13-msgtype", label: "Message Type", detail: "Echo Request (1)" },
          { id: "f13-teid", label: "TEID", detail: "0x00000000 (path management, not tunnel-scoped)" },
        ],
      },
    ],
  },
  {
    frameNumber: 14,
    timestamp: "2026-08-19T01:05:12.390615Z",
    epochMicroseconds: 1755565512390615,
    srcIp: "192.0.2.40",
    srcPort: 2152,
    dstIp: "192.0.2.10",
    dstPort: 2152,
    protocol: "GTP-U",
    length: 66,
    info: "Echo Response (Session #5)",
    domain: "USER_PLANE_N4_N3",
    correlatedSupi: USER_A_SUPI,
    status: "SUCCESS",
    decodeTree: [
      ...baseLayers({ frameNumber: 14, length: 66, srcIp: "192.0.2.40", srcPort: 2152, dstIp: "192.0.2.10", dstPort: 2152, transport: "UDP" }),
      {
        id: "f14-gtpu",
        label: "GPRS Tunnelling Protocol",
        detail: "Echo Response",
        children: [
          { id: "f14-flags", label: "Flags", detail: "Version 1, PT: GTP, no optional headers" },
          { id: "f14-msgtype", label: "Message Type", detail: "Echo Response (2)" },
          { id: "f14-restart", label: "Recovery (Restart Counter)", detail: "4" },
        ],
      },
    ],
  },

  // ---- Frames 15–21: User A Session #8 (ims) — concurrent with Session #5 ----
  {
    frameNumber: 15,
    timestamp: "2026-08-19T01:05:12.430615Z",
    epochMicroseconds: 1755565512430615,
    srcIp: "192.0.2.20",
    srcPort: 44302,
    dstIp: "192.0.2.30",
    dstPort: 8080,
    protocol: "HTTP2/JSON",
    length: 498,
    info: "POST /nsmf-pdusession/v1/sm-contexts, 201 Created (Session #8)",
    domain: "CORE_SBI",
    correlatedSupi: USER_A_SUPI,
    status: "SUCCESS",
    decodeTree: [
      ...baseLayers({ frameNumber: 15, length: 498, srcIp: "192.0.2.20", srcPort: 44302, dstIp: "192.0.2.30", dstPort: 8080, transport: "TCP" }),
      {
        id: "f15-http2",
        label: "HTTP/2",
        detail: "POST /nsmf-pdusession/v1/sm-contexts",
        children: [
          { id: "f15-h2-status", label: ":status", detail: "201" },
          {
            id: "f15-h2-body",
            label: "JSON Body",
            children: objectToNodes(
              {
                supi: USER_A_SUPI,
                pduSessionId: 8,
                dnn: "ims",
                sNssai: { sst: 1, sd: "000002" },
                anType: "3GPP_ACCESS",
                smContextStatusUri: "http://amf.5gc.mnc001.mcc001.3gppnetwork.org/namf-callback/v1/smContextStatus/8",
              },
              "f15-body",
            ),
          },
        ],
      },
    ],
  },
  {
    frameNumber: 16,
    timestamp: "2026-08-19T01:05:12.465615Z",
    epochMicroseconds: 1755565512465615,
    srcIp: "192.0.2.30",
    srcPort: 8805,
    dstIp: "192.0.2.40",
    dstPort: 8805,
    protocol: "PFCP",
    length: 172,
    info: "Session Establishment Request, 2 PDR, 2 FAR (Session #8)",
    domain: "USER_PLANE_N4_N3",
    correlatedSupi: USER_A_SUPI,
    status: "INFO",
    decodeTree: [
      ...baseLayers({ frameNumber: 16, length: 172, srcIp: "192.0.2.30", srcPort: 8805, dstIp: "192.0.2.40", dstPort: 8805, transport: "UDP" }),
      {
        id: "f16-pfcp",
        label: "Packet Forwarding Control Protocol",
        detail: "Session Establishment Request",
        children: [
          {
            id: "f16-pdr1",
            label: "Create PDR (PDR ID 1)",
            detail: "Precedence 100",
            children: [
              { id: "f16-pdr1-pdi", label: "PDI", detail: "Source Interface: Access, Local F-TEID 0x1A4B8C99, UE IP 192.0.2.155" },
              { id: "f16-pdr1-far", label: "FAR ID", detail: "1" },
            ],
          },
          {
            id: "f16-pdr2",
            label: "Create PDR (PDR ID 2)",
            detail: "Precedence 100",
            children: [
              { id: "f16-pdr2-pdi", label: "PDI", detail: "Source Interface: Core, Network Instance ims" },
              { id: "f16-pdr2-far", label: "FAR ID", detail: "2" },
            ],
          },
          {
            id: "f16-far1",
            label: "Create FAR (FAR ID 1)",
            detail: "Apply Action: FORW",
            children: [{ id: "f16-far1-fp", label: "Forwarding Parameters", detail: "Destination Interface: Core" }],
          },
          {
            id: "f16-far2",
            label: "Create FAR (FAR ID 2)",
            detail: "Apply Action: FORW",
            children: [
              { id: "f16-far2-fp", label: "Forwarding Parameters", detail: "Destination Interface: Access, Outer Header Creation: GTP-U/UDP/IPv4 TEID 0x99A8B7C1" },
            ],
          },
        ],
      },
    ],
  },
  {
    frameNumber: 17,
    timestamp: "2026-08-19T01:05:12.490615Z",
    epochMicroseconds: 1755565512490615,
    srcIp: "192.0.2.40",
    srcPort: 8805,
    dstIp: "192.0.2.30",
    dstPort: 8805,
    protocol: "PFCP",
    length: 106,
    info: "Session Establishment Response, Cause: Request accepted (Session #8)",
    domain: "USER_PLANE_N4_N3",
    correlatedSupi: USER_A_SUPI,
    status: "SUCCESS",
    decodeTree: [
      ...baseLayers({ frameNumber: 17, length: 106, srcIp: "192.0.2.40", srcPort: 8805, dstIp: "192.0.2.30", dstPort: 8805, transport: "UDP" }),
      {
        id: "f17-pfcp",
        label: "Packet Forwarding Control Protocol",
        detail: "Session Establishment Response",
        children: [
          { id: "f17-cause", label: "Cause", detail: "Request accepted" },
          { id: "f17-fteid", label: "Created PDR (PDR ID 1)", detail: "Assigned F-TEID 0x1A4B8C99" },
        ],
      },
    ],
  },
  {
    frameNumber: 18,
    timestamp: "2026-08-19T01:05:12.520615Z",
    epochMicroseconds: 1755565512520615,
    srcIp: "192.0.2.30",
    srcPort: 44303,
    dstIp: "192.0.2.20",
    dstPort: 8080,
    protocol: "HTTP2/JSON",
    length: 298,
    info: "POST /nsmf-pdusession/v1/sm-contexts/8/modify, 200 OK",
    domain: "CORE_SBI",
    correlatedSupi: USER_A_SUPI,
    status: "SUCCESS",
    decodeTree: [
      ...baseLayers({ frameNumber: 18, length: 298, srcIp: "192.0.2.30", srcPort: 44303, dstIp: "192.0.2.20", dstPort: 8080, transport: "TCP" }),
      {
        id: "f18-http2",
        label: "HTTP/2",
        detail: "POST /nsmf-pdusession/v1/sm-contexts/8/modify",
        children: [
          { id: "f18-h2-status", label: ":status", detail: "200" },
          {
            id: "f18-h2-body",
            label: "JSON Body",
            children: objectToNodes(
              { pduSessionId: 8, upCnxState: "ACTIVATED", n2SmInfoType: "PDU_RES_SETUP_REQ", n1SmMsgType: "PDU_SESSION_ESTABLISHMENT_ACCEPT" },
              "f18-body",
            ),
          },
        ],
      },
    ],
  },
  {
    frameNumber: 19,
    timestamp: "2026-08-19T01:05:12.548615Z",
    epochMicroseconds: 1755565512548615,
    srcIp: "192.0.2.20",
    srcPort: 38412,
    dstIp: "192.0.2.10",
    dstPort: 51001,
    protocol: "NGAP",
    length: 180,
    info: "PDUSessionResourceSetupRequest, PDU Session ID: 8",
    domain: "ACCESS_N1_N2",
    correlatedSupi: USER_A_SUPI,
    status: "INFO",
    decodeTree: [
      ...baseLayers({ frameNumber: 19, length: 180, srcIp: "192.0.2.20", srcPort: 38412, dstIp: "192.0.2.10", dstPort: 51001, transport: "SCTP" }),
      {
        id: "f19-ngap",
        label: "NG Application Protocol",
        detail: "PDUSessionResourceSetupRequest",
        children: [
          { id: "f19-amfid", label: "AMF-UE-NGAP-ID", detail: "500219" },
          { id: "f19-ranid", label: "RAN-UE-NGAP-ID", detail: "1042" },
          {
            id: "f19-list",
            label: "PDUSessionResourceSetupListSUReq",
            detail: "1 item",
            children: [
              { id: "f19-pdusid", label: "PDUSessionID", detail: "8" },
              { id: "f19-ul-tnl", label: "UL-NGU-UP-TNLInformation", detail: "GTP-TEID 0x1A4B8C99, transportLayerAddress 192.0.2.40" },
            ],
          },
        ],
      },
    ],
  },
  {
    frameNumber: 20,
    timestamp: "2026-08-19T01:05:12.583615Z",
    epochMicroseconds: 1755565512583615,
    srcIp: "192.0.2.10",
    srcPort: 2152,
    dstIp: "192.0.2.40",
    dstPort: 2152,
    protocol: "GTP-U",
    length: 62,
    info: "Echo Request (Session #8)",
    domain: "USER_PLANE_N4_N3",
    correlatedSupi: USER_A_SUPI,
    status: "INFO",
    decodeTree: [
      ...baseLayers({ frameNumber: 20, length: 62, srcIp: "192.0.2.10", srcPort: 2152, dstIp: "192.0.2.40", dstPort: 2152, transport: "UDP" }),
      {
        id: "f20-gtpu",
        label: "GPRS Tunnelling Protocol",
        detail: "Echo Request",
        children: [
          { id: "f20-flags", label: "Flags", detail: "Version 1, PT: GTP, no optional headers" },
          { id: "f20-msgtype", label: "Message Type", detail: "Echo Request (1)" },
          { id: "f20-teid", label: "TEID", detail: "0x00000000 (path management, not tunnel-scoped)" },
        ],
      },
    ],
  },
  {
    frameNumber: 21,
    timestamp: "2026-08-19T01:05:12.605615Z",
    epochMicroseconds: 1755565512605615,
    srcIp: "192.0.2.40",
    srcPort: 2152,
    dstIp: "192.0.2.10",
    dstPort: 2152,
    protocol: "GTP-U",
    length: 66,
    info: "Echo Response (Session #8)",
    domain: "USER_PLANE_N4_N3",
    correlatedSupi: USER_A_SUPI,
    status: "SUCCESS",
    decodeTree: [
      ...baseLayers({ frameNumber: 21, length: 66, srcIp: "192.0.2.40", srcPort: 2152, dstIp: "192.0.2.10", dstPort: 2152, transport: "UDP" }),
      {
        id: "f21-gtpu",
        label: "GPRS Tunnelling Protocol",
        detail: "Echo Response",
        children: [
          { id: "f21-flags", label: "Flags", detail: "Version 1, PT: GTP, no optional headers" },
          { id: "f21-msgtype", label: "Message Type", detail: "Echo Response (2)" },
          { id: "f21-restart", label: "Recovery (Restart Counter)", detail: "4" },
        ],
      },
    ],
  },

  // ---- Frames 22–24: User C — mid-stream capture, no Registration observed ----
  {
    frameNumber: 22,
    timestamp: "2026-08-19T01:05:12.655615Z",
    epochMicroseconds: 1755565512655615,
    srcIp: "192.0.2.30",
    srcPort: 44305,
    dstIp: "192.0.2.20",
    dstPort: 8080,
    protocol: "HTTP2/JSON",
    length: 286,
    info: "POST /nsmf-pdusession/v1/sm-contexts/12/modify, 200 OK",
    domain: "CORE_SBI",
    correlatedSupi: USER_C_SUPI,
    status: "INFO",
    decodeTree: [
      ...baseLayers({ frameNumber: 22, length: 286, srcIp: "192.0.2.30", srcPort: 44305, dstIp: "192.0.2.20", dstPort: 8080, transport: "TCP" }),
      {
        id: "f22-http2",
        label: "HTTP/2",
        detail: "POST /nsmf-pdusession/v1/sm-contexts/12/modify",
        children: [
          { id: "f22-h2-status", label: ":status", detail: "200" },
          {
            id: "f22-h2-body",
            label: "JSON Body",
            children: objectToNodes(
              { pduSessionId: 12, upCnxState: "ACTIVATED", n2SmInfoType: "PDU_RES_MOD_REQ", n1SmMsgType: "PDU_SESSION_MODIFICATION_COMMAND" },
              "f22-body",
            ),
          },
        ],
      },
    ],
  },
  {
    frameNumber: 23,
    timestamp: "2026-08-19T01:05:12.673615Z",
    epochMicroseconds: 1755565512673615,
    srcIp: "192.0.2.10",
    srcPort: 2152,
    dstIp: "192.0.2.40",
    dstPort: 2152,
    protocol: "GTP-U",
    length: 890,
    info: "G-PDU, TEID: 0x77CC2201 (uplink user data, tunnel pre-existing)",
    domain: "USER_PLANE_N4_N3",
    correlatedSupi: USER_C_SUPI,
    status: "INFO",
    decodeTree: [
      ...baseLayers({ frameNumber: 23, length: 890, srcIp: "192.0.2.10", srcPort: 2152, dstIp: "192.0.2.40", dstPort: 2152, transport: "UDP" }),
      {
        id: "f23-gtpu",
        label: "GPRS Tunnelling Protocol",
        detail: "G-PDU",
        children: [
          { id: "f23-flags", label: "Flags", detail: "Version 1, PT: GTP, no optional headers" },
          { id: "f23-msgtype", label: "Message Type", detail: "G-PDU (255)" },
          { id: "f23-teid", label: "TEID", detail: "0x77CC2201" },
          { id: "f23-payload", label: "T-PDU", detail: "IPv4 user payload (opaque to this capture point)" },
        ],
      },
    ],
  },
  {
    frameNumber: 24,
    timestamp: "2026-08-19T01:05:12.688615Z",
    epochMicroseconds: 1755565512688615,
    srcIp: "192.0.2.40",
    srcPort: 2152,
    dstIp: "192.0.2.10",
    dstPort: 2152,
    protocol: "GTP-U",
    length: 1240,
    info: "G-PDU, TEID: 0x33DD4402 (downlink user data, tunnel pre-existing)",
    domain: "USER_PLANE_N4_N3",
    correlatedSupi: USER_C_SUPI,
    status: "SUCCESS",
    decodeTree: [
      ...baseLayers({ frameNumber: 24, length: 1240, srcIp: "192.0.2.40", srcPort: 2152, dstIp: "192.0.2.10", dstPort: 2152, transport: "UDP" }),
      {
        id: "f24-gtpu",
        label: "GPRS Tunnelling Protocol",
        detail: "G-PDU",
        children: [
          { id: "f24-flags", label: "Flags", detail: "Version 1, PT: GTP, no optional headers" },
          { id: "f24-msgtype", label: "Message Type", detail: "G-PDU (255)" },
          { id: "f24-teid", label: "TEID", detail: "0x33DD4402" },
          { id: "f24-payload", label: "T-PDU", detail: "IPv4 user payload (opaque to this capture point)" },
        ],
      },
    ],
  },

  // ---- Frames 25–30: background noise — no correlatedSupi at all ----
  {
    frameNumber: 25,
    timestamp: "2026-08-19T01:05:12.700615Z",
    epochMicroseconds: 1755565512700615,
    srcIp: "192.0.2.62",
    srcPort: 53,
    dstIp: "192.0.2.109",
    dstPort: 51820,
    protocol: "DNS",
    length: 98,
    info: "Standard query response 0x1a2b A 198.51.100.20",
    domain: "USER_PLANE_N4_N3",
    status: "INFO",
    decodeTree: [
      ...baseLayers({ frameNumber: 25, length: 98, srcIp: "192.0.2.62", srcPort: 53, dstIp: "192.0.2.109", dstPort: 51820, transport: "UDP" }),
      {
        id: "f25-dns",
        label: "Domain Name System",
        detail: "Standard query response 0x1a2b A 198.51.100.20",
        children: [
          { id: "f25-dns-q", label: "Queries", children: [{ id: "f25-dns-qname", label: "Name", detail: "pool.ntp.mnc001.mcc001.gprs" }] },
          { id: "f25-dns-a", label: "Answers", children: [{ id: "f25-dns-addr", label: "Address", detail: "198.51.100.20" }] },
        ],
      },
    ],
  },
  {
    frameNumber: 26,
    timestamp: "2026-08-19T01:05:12.720615Z",
    epochMicroseconds: 1755565512720615,
    srcIp: "192.0.2.109",
    srcPort: 123,
    dstIp: "192.0.2.63",
    dstPort: 123,
    protocol: "NTP",
    length: 48,
    info: "NTP Version 4, client",
    domain: "USER_PLANE_N4_N3",
    status: "INFO",
    decodeTree: [
      ...baseLayers({ frameNumber: 26, length: 48, srcIp: "192.0.2.109", srcPort: 123, dstIp: "192.0.2.63", dstPort: 123, transport: "UDP" }),
      {
        id: "f26-ntp",
        label: "Network Time Protocol",
        detail: "NTP Version 4, client",
        children: [
          { id: "f26-ntp-flags", label: "Flags", detail: "LI 0, VN 4, Mode 3 (client)" },
          { id: "f26-ntp-stratum", label: "Peer Clock Stratum", detail: "0 (unspecified)" },
        ],
      },
    ],
  },
  {
    frameNumber: 27,
    timestamp: "2026-08-19T01:05:12.738615Z",
    epochMicroseconds: 1755565512738615,
    srcIp: "192.0.2.63",
    srcPort: 123,
    dstIp: "192.0.2.109",
    dstPort: 123,
    protocol: "NTP",
    length: 48,
    info: "NTP Version 4, server",
    domain: "USER_PLANE_N4_N3",
    status: "SUCCESS",
    decodeTree: [
      ...baseLayers({ frameNumber: 27, length: 48, srcIp: "192.0.2.63", srcPort: 123, dstIp: "192.0.2.109", dstPort: 123, transport: "UDP" }),
      {
        id: "f27-ntp",
        label: "Network Time Protocol",
        detail: "NTP Version 4, server",
        children: [
          { id: "f27-ntp-flags", label: "Flags", detail: "LI 0, VN 4, Mode 4 (server)" },
          { id: "f27-ntp-stratum", label: "Peer Clock Stratum", detail: "2" },
        ],
      },
    ],
  },
  {
    frameNumber: 28,
    timestamp: "2026-08-19T01:05:12.753615Z",
    epochMicroseconds: 1755565512753615,
    srcIp: "192.0.2.21",
    srcPort: 0,
    dstIp: "255.255.255.255",
    dstPort: 0,
    protocol: "ARP",
    length: 42,
    info: "Who has 192.0.2.20? Tell 192.0.2.21",
    domain: "USER_PLANE_N4_N3",
    status: "INFO",
    decodeTree: [
      { id: "f28-frame", label: "Frame 28", detail: "42 bytes on wire (336 bits)" },
      { id: "f28-eth", label: "Ethernet II", detail: "capture point: core-network mirror port, Type: ARP (0x0806)" },
      {
        id: "f28-arp",
        label: "Address Resolution Protocol (request)",
        detail: "Who has 192.0.2.20? Tell 192.0.2.21",
        children: [
          { id: "f28-arp-op", label: "Opcode", detail: "request (1)" },
          { id: "f28-arp-sender-ip", label: "Sender IP address", detail: "192.0.2.21" },
          { id: "f28-arp-target-ip", label: "Target IP address", detail: "192.0.2.20" },
        ],
      },
    ],
  },
  {
    frameNumber: 29,
    timestamp: "2026-08-19T01:05:12.761615Z",
    epochMicroseconds: 1755565512761615,
    srcIp: "192.0.2.20",
    srcPort: 0,
    dstIp: "192.0.2.21",
    dstPort: 0,
    protocol: "ARP",
    length: 42,
    info: "192.0.2.20 is at 02:1a:2b:3c:4d:5e",
    domain: "USER_PLANE_N4_N3",
    status: "SUCCESS",
    decodeTree: [
      { id: "f29-frame", label: "Frame 29", detail: "42 bytes on wire (336 bits)" },
      { id: "f29-eth", label: "Ethernet II", detail: "capture point: core-network mirror port, Type: ARP (0x0806)" },
      {
        id: "f29-arp",
        label: "Address Resolution Protocol (reply)",
        detail: "192.0.2.20 is at 02:1a:2b:3c:4d:5e",
        children: [
          { id: "f29-arp-op", label: "Opcode", detail: "reply (2)" },
          { id: "f29-arp-sender-mac", label: "Sender MAC address", detail: "02:1a:2b:3c:4d:5e" },
          { id: "f29-arp-sender-ip", label: "Sender IP address", detail: "192.0.2.20" },
        ],
      },
    ],
  },
  {
    frameNumber: 30,
    timestamp: "2026-08-19T01:05:12.801615Z",
    epochMicroseconds: 1755565512801615,
    srcIp: "192.0.2.20",
    srcPort: 44400,
    dstIp: "192.0.2.70",
    dstPort: 8080,
    protocol: "HTTP2/JSON",
    length: 356,
    info: "GET /nnrf-disc/v1/nf-instances?target-nf-type=SMF, 200 OK",
    domain: "CORE_SBI",
    status: "SUCCESS",
    decodeTree: [
      ...baseLayers({ frameNumber: 30, length: 356, srcIp: "192.0.2.20", srcPort: 44400, dstIp: "192.0.2.70", dstPort: 8080, transport: "TCP" }),
      {
        id: "f30-http2",
        label: "HTTP/2",
        detail: "GET /nnrf-disc/v1/nf-instances?target-nf-type=SMF",
        children: [
          { id: "f30-h2-status", label: ":status", detail: "200" },
          {
            id: "f30-h2-body",
            label: "JSON Body",
            children: objectToNodes({ validityPeriod: 300, nfInstances: [{ nfInstanceId: "smf-a1", nfType: "SMF", nfStatus: "REGISTERED" }] }, "f30-body"),
          },
        ],
      },
    ],
  },
];

const rawPackets: RawPacket[] = packetSeeds.map((seed) => ({
  ...seed,
  decodeTree: assignByteRanges(seed.decodeTree ?? [], 0, seed.length),  // decodeTree 在型別上已改為選用（真實資料是懶載入的）；手寫的 seed 一律有
  hexDump: generateHexDump(seed.frameNumber, seed.length),
}));

// ---------------------------------------------------------------------------
// Call flow events — every entry anchors to a real rawPackets[].frameNumber
// ---------------------------------------------------------------------------

const callFlowEvents: CallFlowEvent[] = [
  // User A — Session #5 (internet)
  {
    id: "evt-1",
    frameNumber: 2,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.112384Z",
    fromNode: "gNB",
    toNode: "AMF",
    messageName: "InitialUEMessage (Registration Request)",
    interfaceName: "N2",
    domain: "ACCESS_N1_N2",
    status: "INFO",
    summary: "gNB 轉送 UE 的 Registration Request 至 AMF，內含 SUCI",
  },
  {
    id: "evt-2",
    frameNumber: 4,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.134221Z",
    fromNode: "AMF",
    toNode: "AUSF",
    messageName: "Nausf_UEAuthentication_Authenticate",
    interfaceName: "N12",
    domain: "CORE_SBI",
    status: "SUCCESS",
    summary: "AMF 向 AUSF 請求 5G-AKA 認證向量",
  },
  {
    id: "evt-3",
    frameNumber: 6,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.158652Z",
    fromNode: "AMF",
    toNode: "gNB",
    messageName: "DownlinkNASTransport (Auth Request)",
    interfaceName: "N2",
    domain: "ACCESS_N1_N2",
    status: "INFO",
    summary: "AMF 下發 Authentication Request（RAND/AUTN）",
  },
  {
    id: "evt-4",
    frameNumber: 7,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.191340Z",
    fromNode: "gNB",
    toNode: "AMF",
    messageName: "UplinkNASTransport (Auth Response)",
    interfaceName: "N2",
    domain: "ACCESS_N1_N2",
    status: "SUCCESS",
    summary: "UE 回覆 RES*，認證完成",
  },
  {
    id: "evt-5",
    frameNumber: 8,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.220981Z",
    fromNode: "AMF",
    toNode: "SMF",
    messageName: "Nsmf_PDUSession_CreateSMContext (#5)",
    interfaceName: "N11",
    domain: "CORE_SBI",
    status: "SUCCESS",
    summary: "AMF 請求 SMF 建立 SM Context（Session #5, DNN: internet）",
  },
  {
    id: "evt-6",
    frameNumber: 9,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.256410Z",
    fromNode: "SMF",
    toNode: "UPF",
    messageName: "PFCP Session Establishment Request (#5)",
    interfaceName: "N4",
    domain: "USER_PLANE_N4_N3",
    status: "INFO",
    summary: "SMF 下發 PDR/FAR 規則要求 UPF 建立轉發規則",
  },
  {
    id: "evt-7",
    frameNumber: 10,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.279650Z",
    fromNode: "UPF",
    toNode: "SMF",
    messageName: "PFCP Session Establishment Response (#5)",
    interfaceName: "N4",
    domain: "USER_PLANE_N4_N3",
    status: "SUCCESS",
    summary: "UPF 確認建立，回傳分配的 F-TEID",
  },
  {
    id: "evt-8",
    frameNumber: 11,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.304822Z",
    fromNode: "SMF",
    toNode: "AMF",
    messageName: "Nsmf_PDUSession_UpdateSMContext (Accept, #5)",
    interfaceName: "N11",
    domain: "CORE_SBI",
    status: "SUCCESS",
    summary: "SMF 通知 AMF 使用者面已就緒，可建立 N2 資源",
  },
  {
    id: "evt-9",
    frameNumber: 12,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.331509Z",
    fromNode: "AMF",
    toNode: "gNB",
    messageName: "PDUSessionResourceSetupRequest (#5)",
    interfaceName: "N2",
    domain: "ACCESS_N1_N2",
    status: "INFO",
    summary: "AMF 要求 gNB 建立對應的 N3 資源與 TEID",
  },
  {
    id: "evt-10",
    frameNumber: 13,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.368274Z",
    fromNode: "gNB",
    toNode: "UPF",
    messageName: "GTP-U Echo Request (#5)",
    interfaceName: "N3",
    domain: "USER_PLANE_N4_N3",
    status: "INFO",
    summary: "驗證 gNB-UPF 間 N3 GTP-U 通道存活",
  },
  {
    id: "evt-11",
    frameNumber: 14,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.390615Z",
    fromNode: "UPF",
    toNode: "gNB",
    messageName: "GTP-U Echo Response (#5)",
    interfaceName: "N3",
    domain: "USER_PLANE_N4_N3",
    status: "SUCCESS",
    summary: "Session #5（internet）建立完成",
  },
  // User A — Session #8 (ims), concurrent with #5
  {
    id: "evt-12",
    frameNumber: 15,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.430615Z",
    fromNode: "AMF",
    toNode: "SMF",
    messageName: "Nsmf_PDUSession_CreateSMContext (#8)",
    interfaceName: "N11",
    domain: "CORE_SBI",
    status: "SUCCESS",
    summary: "同一用戶請求第二個併發 PDU Session（Session #8, DNN: ims）",
  },
  {
    id: "evt-13",
    frameNumber: 16,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.465615Z",
    fromNode: "SMF",
    toNode: "UPF",
    messageName: "PFCP Session Establishment Request (#8)",
    interfaceName: "N4",
    domain: "USER_PLANE_N4_N3",
    status: "INFO",
    summary: "SMF 為 IMS PDU Session 下發 PDR/FAR",
  },
  {
    id: "evt-14",
    frameNumber: 17,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.490615Z",
    fromNode: "UPF",
    toNode: "SMF",
    messageName: "PFCP Session Establishment Response (#8)",
    interfaceName: "N4",
    domain: "USER_PLANE_N4_N3",
    status: "SUCCESS",
    summary: "UPF 確認建立，回傳 IMS session 的 F-TEID",
  },
  {
    id: "evt-15",
    frameNumber: 18,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.520615Z",
    fromNode: "SMF",
    toNode: "AMF",
    messageName: "Nsmf_PDUSession_UpdateSMContext (Accept, #8)",
    interfaceName: "N11",
    domain: "CORE_SBI",
    status: "SUCCESS",
    summary: "SMF 通知 AMF IMS 使用者面已就緒",
  },
  {
    id: "evt-16",
    frameNumber: 19,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.548615Z",
    fromNode: "AMF",
    toNode: "gNB",
    messageName: "PDUSessionResourceSetupRequest (#8)",
    interfaceName: "N2",
    domain: "ACCESS_N1_N2",
    status: "INFO",
    summary: "AMF 要求 gNB 為 IMS session 建立第二組 N3 資源",
  },
  {
    id: "evt-17",
    frameNumber: 20,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.583615Z",
    fromNode: "gNB",
    toNode: "UPF",
    messageName: "GTP-U Echo Request (#8)",
    interfaceName: "N3",
    domain: "USER_PLANE_N4_N3",
    status: "INFO",
    summary: "驗證 IMS session 的 N3 GTP-U 通道存活",
  },
  {
    id: "evt-18",
    frameNumber: 21,
    supi: USER_A_SUPI,
    timestamp: "2026-08-19T01:05:12.605615Z",
    fromNode: "UPF",
    toNode: "gNB",
    messageName: "GTP-U Echo Response (#8)",
    interfaceName: "N3",
    domain: "USER_PLANE_N4_N3",
    status: "SUCCESS",
    summary: "Session #8（ims）建立完成，用戶現有 2 個併發 PDU Session",
  },
  // User B — Registration Reject
  {
    id: "evt-b1",
    frameNumber: 3,
    supi: USER_B_SUPI,
    timestamp: "2026-08-19T01:05:12.118940Z",
    fromNode: "gNB",
    toNode: "AMF",
    messageName: "InitialUEMessage (Registration Request)",
    interfaceName: "N2",
    domain: "ACCESS_N1_N2",
    status: "INFO",
    summary: "gNB 轉送另一 UE 的 Registration Request 至 AMF",
  },
  {
    id: "evt-b2",
    frameNumber: 5,
    supi: USER_B_SUPI,
    timestamp: "2026-08-19T01:05:12.151077Z",
    fromNode: "AMF",
    toNode: "gNB",
    messageName: "DownlinkNASTransport (Registration Reject)",
    interfaceName: "N2",
    domain: "ACCESS_N1_N2",
    status: "ERROR",
    summary: "AMF 拒絕註冊，未建立任何 PDU Session",
    causeText: "5GS Cause #11 (PLMN not allowed)",
    causeNodeId: "f5-cause",
  },
  // User C — mid-stream capture, no Registration observed
  {
    id: "evt-c1",
    frameNumber: 22,
    supi: USER_C_SUPI,
    timestamp: "2026-08-19T01:05:12.655615Z",
    fromNode: "SMF",
    toNode: "AMF",
    messageName: "Nsmf_PDUSession_UpdateSMContext (Modification)",
    interfaceName: "N11",
    domain: "CORE_SBI",
    status: "INFO",
    summary: "擷取起點即為此則 Update —— 先前的 Registration/CreateSMContext 未被捕獲",
  },
  {
    id: "evt-c2",
    frameNumber: 23,
    supi: USER_C_SUPI,
    timestamp: "2026-08-19T01:05:12.673615Z",
    fromNode: "gNB",
    toNode: "UPF",
    messageName: "GTP-U Data (G-PDU, Uplink)",
    interfaceName: "N3",
    domain: "USER_PLANE_N4_N3",
    status: "INFO",
    summary: "使用者面資料，通道已存在於擷取開始前",
  },
  {
    id: "evt-c3",
    frameNumber: 24,
    supi: USER_C_SUPI,
    timestamp: "2026-08-19T01:05:12.688615Z",
    fromNode: "UPF",
    toNode: "gNB",
    messageName: "GTP-U Data (G-PDU, Downlink)",
    interfaceName: "N3",
    domain: "USER_PLANE_N4_N3",
    status: "SUCCESS",
    summary: "下行使用者面資料流",
  },
];

// ---------------------------------------------------------------------------
// Correlation entries — one per PDU Session, not one per user
// ---------------------------------------------------------------------------

const correlationEntries: CorrelationEntry[] = [
  {
    supi: USER_A_SUPI,
    guti: "001-01-8001-0002-C3F1A9",
    pduSessionId: 5,
    sNssai: { sst: 1, sd: "000001" },
    dnn: "internet",
    ueIp: "192.0.2.122",
    upfN3Teid: "0x2F3A9C11",
    gnbN3Teid: "0x88F10A02",
    qosFlowId: 1,
    fiveQi: 9,
    sourceInterfaces: {
      supi: "AMF N12 (Nausf_UEAuthentication)",
      guti: "AMF N2 (InitialUEMessage)",
      pduSessionId: "SMF N11 (Nsmf_PDUSession_CreateSMContext)",
      sNssai: "SMF N11 (Nsmf_PDUSession_CreateSMContext)",
      dnn: "SMF N11 (Nsmf_PDUSession_CreateSMContext)",
      ueIp: "SMF N4 (PFCP Session Establishment Response)",
      upfN3Teid: "UPF N4 (PFCP Session Establishment Response, F-TEID)",
      gnbN3Teid: "AMF N2 (PDU Session Resource Setup Response)",
      qosFlowId: "SMF N11 (Nsmf_PDUSession_CreateSMContext)",
    },
  },
  {
    supi: USER_A_SUPI,
    guti: "001-01-8001-0002-C3F1A9",
    pduSessionId: 8,
    sNssai: { sst: 1, sd: "000002" },
    dnn: "ims",
    ueIp: "192.0.2.155",
    upfN3Teid: "0x1A4B8C99",
    gnbN3Teid: "0x99A8B7C1",
    qosFlowId: 2,
    fiveQi: 5,
    sourceInterfaces: {
      supi: "AMF N12 (Nausf_UEAuthentication)",
      guti: "AMF N2 (InitialUEMessage)",
      pduSessionId: "SMF N11 (Nsmf_PDUSession_CreateSMContext)",
      sNssai: "SMF N11 (Nsmf_PDUSession_CreateSMContext)",
      dnn: "SMF N11 (Nsmf_PDUSession_CreateSMContext)",
      ueIp: "SMF N4 (PFCP Session Establishment Response)",
      upfN3Teid: "UPF N4 (PFCP Session Establishment Response, F-TEID)",
      gnbN3Teid: "AMF N2 (PDU Session Resource Setup Response)",
      qosFlowId: "SMF N11 (Nsmf_PDUSession_CreateSMContext)",
    },
  },
  {
    supi: USER_C_SUPI,
    // no guti — never observed; this is a mid-stream capture (see SessionIdentity.captureStatus)
    pduSessionId: 12,
    sNssai: { sst: 1, sd: "000001" },
    dnn: "internet",
    ueIp: "192.0.2.140",
    upfN3Teid: "0x77CC2201",
    gnbN3Teid: "0x33DD4402",
    qosFlowId: 1,
    fiveQi: 9,
    sourceInterfaces: {
      supi: "推定（無 Registration 觀測，經既有 N4/N3 規則反查）",
      pduSessionId: "SMF N11 (Nsmf_PDUSession_UpdateSMContext)",
      sNssai: "推定值（未觀測到建立階段）",
      dnn: "SMF N11 (Nsmf_PDUSession_UpdateSMContext)",
      ueIp: "N4 PDR（既有轉發規則回推）",
      upfN3Teid: "N3 GTP-U 封包標頭（TEID 直讀）",
      gnbN3Teid: "N3 GTP-U 封包標頭（TEID 直讀）",
      qosFlowId: "推定值（未觀測到建立階段）",
    },
  },
];

export const mockData: MockDataset = {
  sessionIdentities,
  callFlowEvents,
  correlationEntries,
  rawPackets,
};
